src/main/urls.py
from django.conf.urls import url

from .views import IncomingDataIndexView, IncomingDataAPIView, IncomingDataList


__all__ = ['urlpatterns']


urlpatterns = [
    url(r'^$', IncomingDataIndexView.as_view(), name='index-page'),
    url(r'^API/list/$', IncomingDataList.as_view(), name='list-text'),
    url(r'^API/uploadText/$', IncomingDataAPIView.as_view(), name='upload-text'),
    url(r'^API/getText/$', IncomingDataAPIView.as_view(), name='get-text'),
]

src/urls.py
from django.conf.urls import url, include
from django.contrib import admin


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('src.main.urls')),
]

src/main/models.py
from rest_framework import serializers

from django.db import models


class IncomingData(models.Model):
    created = models.DateTimeField(auto_now_add=True, blank=True)
    text = models.TextField()

    def to_dict(self):
        return dict(
            id=self.id,
            created=self.created.isoformat(sep=' ')[:19],
            text=self.text
        )


class IncomingDataSerializer(serializers.Serializer):
    id = serializers.IntegerField(read_only=True)
    created = serializers.DateTimeField(
        format='%Y-%m-%d %H:%M:%S', required=False)
    text = serializers.CharField()

    def create(self, validated_data):
        return IncomingData.objects.create(**validated_data)

src/main/views.py
from django.views.generic import TemplateView
from rest_framework.generics import CreateAPIView, RetrieveAPIView, \
    ListCreateAPIView

from .models import IncomingData, IncomingDataSerializer


class IncomingDataIndexView(TemplateView):
    template_name = 'index.html'


class IncomingDataList(ListCreateAPIView):
    queryset = IncomingData.objects.all()
    serializer_class = IncomingDataSerializer


class IncomingDataAPIView(CreateAPIView, RetrieveAPIView):
    serializer_class = IncomingDataSerializer

src/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>KVADRA Test app</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
          integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u"
          crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/knockout/3.4.1/knockout-min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"
            integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa"
            crossorigin="anonymous"></script>

</head>
<body>
    <div class="row">
        <div class="col-md-1"></div>
        <div class="col-md-10">
            <button class="btn btn-default btn-sm"
                    data-bind="click: form.open">
                Send text
            </button>
            <table class="table table-condensed">
            <thead><tr>
                <th>ID</th>
                <th>Created</th>
                <th>Text</th>
            </tr></thead>
            <tbody data-bind="foreach: objectsList">
                <tr >
                    <td data-bind="text: id"></td>
                    <td data-bind="text: created"></td>
                    <td data-bind="text: text"></td>
                </tr>
            </tbody>
            </table>
        </div>
        <div class="col-md-1"></div>
    </div>

    <div class="modal fade bs-example-modal-lg" tabindex="-1" role="dialog"
         id="id_postModal">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal"
                            aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                    <h4 class="modal-title">Send text</h4>
                </div>
                <div class="modal-body">
                    <div class="alert alert-danger" role="alert"
                         data-bind="html: form.error,
                                    visible: form.error().length > 0"></div>
                    <div class="form-group">
                        <label for="id_text">Text</label>
                        <textarea class="form-control" id="id_text"
                               data-bind="value: form.text"></textarea>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default"
                            data-dismiss="modal">Close</button>
                    <button type="button" class="btn btn-primary"
                            data-bind="click: form.post">
                        Send
                    </button>
                </div>
            </div><!-- /.modal-content -->
        </div><!-- /.modal-dialog -->
    </div><!-- /.modal -->

</body>
<script type="application/javascript">
    $(document).ready(function(){
        $.ajaxSetup({
             beforeSend: function(xhr, settings) {
                 function getCookie(name) {
                     var cookieValue = null;
                     if (document.cookie && document.cookie != '') {
                         var cookies = document.cookie.split(';');
                         for (var i = 0; i < cookies.length; i++) {
                             var cookie = jQuery.trim(cookies[i]);
                             // Does this cookie string begin with the name we want?
                             if (cookie.substring(0, name.length + 1) == (name + '=')) {
                                 cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                                 break;
                             }
                         }
                     }
                     return cookieValue;
                 }
                 if (!(/^http:.*/.test(settings.url) || /^https:.*/.test(settings.url))) {
                     // Only send the token to relative URLs i.e. locally.
                     xhr.setRequestHeader("X-CSRFToken", getCookie('csrftoken'));
                 }
             }
        });

        var KVADRATest = function(){
            var self = this;

            self.objectsList = ko.observableArray([]);

            self.getObjects = function(){
                $.ajax({
                    url: '/API/list/',
                    dataType: 'JSON',
                    success: function(rs){
                        self.objectsList.removeAll();
                        for(var i = 0; i < rs.length; i++){
                            self.objectsList.push(rs[i]);
                        }
                    }
                })
            };
            self.getObjects();

            self.form = {
                text: ko.observable(''),
                error: ko.observable(''),

                clear: function(){
                    self.form.error('');
                    self.form.text('');
                },
                isValid: function () {
                    if(!self.form.text() || self.form.text().length == 0){
                        alert('Text is required field!');
                        return false;
                    }
                    return true;
                },
                open: function () {
                    self.form.clear();
                    $('#id_postModal').modal('show');
                },
                post: function(){
                    $.ajax({
                        url: '/API/uploadText/',
                        dataType: 'JSON',
                        type: 'POST',
                        data: {
                            text: self.form.text()
                        },
                        success: function (rs) {
                            self.objectsList.push(rs);
                            self.form.clear();
                            $('#id_postModal').modal('hide');
                        },
                        error: function(a, b, c){
                            var txt = [];
                            if(typeof a.responseJSON == "object"){
                                for(var f in a.responseJSON){
                                    if(a.responseJSON.hasOwnProperty(f)){
                                        txt.push(f + ': ' + a.responseJSON[f])
                                    }
                                }
                                self.form.error(txt.join('<br/>'));
                                console.log(self.form.error())
                            }
                        }
                    })
                }
            };
        };
        ko.applyBindings(KVADRATest());
    });
</script>
</html>